.rubocop.yml:
  default_configs:
    Lint/Void:
      Enabled: false
Gemfile:
  optional:
    ":development":
      - gem: github_changelog_generator
        version: '= 1.16.4'
      - gem: concurrent-ruby
        version: '= 1.1.10'

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.gitlab-ci.yml:
  delete: true
